apiVersion: v1
kind: ServiceAccount
metadata:
  name: contact-form
  namespace: contact-form
automountServiceAccountToken: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: db-verifier
  namespace: contact-form
automountServiceAccountToken: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: db-bootstrap
  namespace: contact-form
automountServiceAccountToken: true
